routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/about', function () {
    return view('About');
});
Route::get('/adults', function () {
    return view('adults');
});

Route::get('/articles', function () {
    return view('articles');
});
Route::get('/blog', function () {
    return view('blog');
});
Route::get('/cause', function () {
    return view('Cause');
});
Route::get('/children_teens', function () {
    return view('children_teens');
});
Route::get('/contact', function () {
    return view('contact');
});
Route::get('/donate', function () {
    return view('donate');
});

Route::get('/events', function () {
    return view('events');
});

Route::get('/gallery', function () {
    return view('gallery');
});
Route::get('/on-site', function () {
    return view('on-site');
});
Route::get('/professionals', function () {
    return view('professionals');
});
Route::get('/single-blog', function () {
    return view('single-blog');
});
Route::get('/testimonials', function () {
    return view('testimonials');
});
Route::get('/volunteer', function () {
    return view('volunteer');
});
Route::get('/contact/index', function () {
    return view('contact/index');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('events','EventsContoller');

app/Events.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    protected $fillable=['title','description','date','time'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EventsContoller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Events;


class EventsContoller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('events.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Events::create( $request->all());
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $events = Events::findOrFail($request->event_id);

        $events->update($request->all());
       
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $events = Events::findOrFail($request->events_id);
        $events->delete();

        return back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/adults.blade.php
<!doctype html>
<html class="no-js" lang="zxx">

<head>
@include('layouts.head')

    <style>
        a.custom-card,
a.custom-card:hover {
  color: inherit;
}
    </style>
</head>

<body>
   <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
    @include('layouts.header')
    </header>
    <!-- header-end -->
  <!-- bradcam_area_start  -->
  <div class="bradcam_area breadcam_bg overlay d-flex align-items-center justify-content-center">
      <div class="container">
          <div class="row">
              <div class="col-xl-12">
                  <div class="bradcam_text text-center">
                      <h3>Adults</h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- bradcam_area_end  -->

  <section>
    <div class="container">
        <h2>Support Groups</h2>
        <hr class="mt-3" style="  border-top: 1px solid #bbb; margin-bottom:-40px;">
  
    <div class="row gap100">
        <div class="col-md-6" >
               
              
                <p>In consideration of unavailability of some individuals to attend support group meetings physically due to
                    distance,geographical location and other unavoidable circumstances, 4Hope Together conducts virtual
                    meetings where members can still come together and talk about their experiences,thoughts and emotions
                    on loss and grief and still offer each other support.</p>
              <br><br>
              <a href="{{ url('contact/index') }}">  <button type="button" class="btn  btn-lg btn-block" style="background:#3cc78f; color:white;">Contact us for more details</button></a>     <br>
       
            
            </div>
        <div class="col-md-6">
           <img src="{{ secure_asset('img/banner/support.jpg') }}" class="img-fluid" alt="">
        </div>
      
       
    </div>

    <!-- <hr class="mt-1 mb-5" style="  border-top: 2px solid #bbb;"> -->
    </div>




</section>

<section>
    <div class="container">
        <h2>Virtual meetings</h2>
        <hr class="mt-3" style="  border-top: 1px solid #bbb; margin-bottom:-40px;">
  
    <div class="row gap100">
        <div class="col-md-6" >
               
              
                <p>In consideration of unavailability of some individuals to attend support group meetings physically due to
                    distance,geographical location and other unavoidable circumstances, 4Hope Together conducts virtual
                    meetings where members can still come together and talk about their experiences,thoughts and emotions
                    on loss and grief and still offer each other support.</p>
              <br><br>
              <a href="{{ url('contact/index') }}">  <button type="button" class="btn  btn-lg btn-block" style="background:#3cc78f; color:white;">Contact us for more details</button></a>    <br>
         
              <div class="card text-center">
                <div class="card-header">
                  Online Meetings
                </div>
                <div class="card-body">
                  <!-- <h5 class="card-title"></h5> -->
                  <p class="card-text">Join us in our next online meeting. Click below to access the zoom meeting link</p>
                  <a href="#" class="btn btn-primary">Click here</a>
                </div>
                <div class="card-footer text-muted">
                  17/02/2000 20:00 E.A.T
                </div>
              </div>
          
          
            </div>
        <div class="col-md-6">
           <img src="{{ secure_asset('img/banner/virtual.jpg') }}" class="img-fluid" alt="">
        </div>
      
       
    </div>

    <hr class="mt-1 mb-5" style="  border-top: 2px solid #bbb;">
    </div>




</section>

    <!-- footer_start  -->
    <footer class="footer">
    @include('layouts.footer')
    </footer>
    <!-- footer_end  -->


   <!-- JS here -->
   <script src="{{ secure_asset('js/vendor/modernizr-3.5.0.min.js') }}"></script>
        <script src="{{ secure_asset('js/vendor/jquery-1.12.4.min.js') }}"></script>
        <script src="{{ secure_asset('js/popper.min.js') }}"></script>
        <script src="{{ secure_asset('js/bootstrap.min.js') }}"></script>
        <script src="{{ secure_asset('js/owl.carousel.min.js') }}"></script>
        <script src="{{ secure_asset('js/isotope.pkgd.min.js') }}"></script>
        <script src="{{ secure_asset('js/ajax-form.js') }}"></script>
        <script src="{{ secure_asset('js/waypoints.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.counterup.min.js') }}"></script>
        <script src="{{ secure_asset('js/imagesloaded.pkgd.min.js') }}"></script>
        <script src="{{ secure_asset('js/scrollIt.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.scrollUp.min.js') }}"></script>
        <script src="{{ secure_asset('js/wow.min.js') }}"></script>
        <script src="{{ secure_asset('js/nice-select.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.slicknav.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.magnific-popup.min.js')}}"></script>
        <script src="{{ secure_asset('js/plugins.js') }}"></script>
        <script src="{{ secure_asset('js/gijgo.min.js') }}"></script>
        <!--contact js-->
        <script src="{{ secure_asset('js/contact.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.ajaxchimp.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.form.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.validate.min.js') }}"></script>
        <script src="{{ secure_asset('js/mail-script.js') }}"></script>

        <script src="{{ secure_asset('js/main.js') }}"></script>
  <script>
      $('.datepicker').datepicker({
          iconsLibrary: 'fontawesome',
          icons: {
              rightIcon: '<span class="fa fa-calendar"></span>'
          }
      });

      $('.timepicker').timepicker({
          iconsLibrary: 'fontawesome',
          icons: {
              rightIcon: '<span class="fa fa-clock-o"></span>'
          }
      });
  </script>
</body>

</html>

resources/views/articles.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
@include('layouts.head')
</head>
<body>
   
    <!-- header-start -->
    <header>
    @include('layouts.header')
    </header>
    <!-- header-end -->

    <!-- bradcam_area_start  -->
    <div class="bradcam_area breadcam_bg overlay d-flex align-items-center justify-content-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <h3>Articles</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- bradcam_area_end  -->
    <section class="news-section">

      <div class="container">
       <!-- <div class="main-title-box text-center">
                     <div class="small-title">News & Blog</div>
                     <h2 class="big-title">Our Recent Artciles</h2>
                 </div> -->
                 <div class="row">
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0ms">
                         <div class="news-item">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/CKNmhMX/blog1.jpg.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Jan 03, 2019</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>The Future of Digital Marketing</h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Robert Tylor </a></span>
                                        
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                         <div class="news-item active">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/m5yGbdR/blog2.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Nov 05, 2018</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>Successful content marketing plan </h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Jessica keri</a></span>
                                        
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="800ms">
                         <div class="news-item">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/YXV3zmh/blog3.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Dec 22, 2018</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>Our agency helps to grow creativity</h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Brandon Auger</a></span>
                                        
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0ms">
                         <div class="news-item">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/CKNmhMX/blog1.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Dec 05, 2017</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>The Future of Digital Marketing</h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Astley Fletcher</a></span>
                                        
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                         <div class="news-item active">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/m5yGbdR/blog2.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Nov 13, 2017</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>Successful content marketing plan </h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Nichel Benjamin</a></span>
                                        
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                     <!--Single Blog Start-->
                     <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="800ms">
                         <div class="news-item">
                             <div class="news_box">
                                 <div class="newsimg"><img class="img-responsive" src="https://i.ibb.co/YXV3zmh/blog3.jpg" alt=""></div>
                                 <div class="news-content">
                                     <div class="news_postdate">
                                         <span>Aug 18, 2017</span>
                                     </div>
                                     <a href="{{ url('single-blog') }}">
                                         <h3>Our agency helps to grow creativity</h3>
                                     </a>
                                     <p>Lorem ipsum dolor sit amet, cons ectet a ur elit. Vestibulum necod ios suspe age a to ndisse cursus mal.</p>
                                     <div class="news_authorinfo">
                                         <span><i class="fa fa-user"></i>  <a href="">Andrew Mickel </a></span>
                                         <span><i class="fa fa-comment"></i> <a href="">Comments: (4)</a></span>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <!--Single Blog End-->
                 </div>
             </div>
         </div>
 </section>
  

    <!-- footer_start  -->
    <footer class="footer">
    @include('layouts.footer')
    </footer>
    <!-- footer_end  -->

  <!-- link that opens popup -->

 <!-- JS here -->
 <script src="{{ secure_asset('js/vendor/modernizr-3.5.0.min.js') }}"></script>
        <script src="{{ secure_asset('js/vendor/jquery-1.12.4.min.js') }}"></script>
        <script src="{{ secure_asset('js/popper.min.js') }}"></script>
        <script src="{{ secure_asset('js/bootstrap.min.js') }}"></script>
        <script src="{{ secure_asset('js/owl.carousel.min.js') }}"></script>
        <script src="{{ secure_asset('js/isotope.pkgd.min.js') }}"></script>
        <script src="{{ secure_asset('js/ajax-form.js') }}"></script>
        <script src="{{ secure_asset('js/waypoints.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.counterup.min.js') }}"></script>
        <script src="{{ secure_asset('js/imagesloaded.pkgd.min.js') }}"></script>
        <script src="{{ secure_asset('js/scrollIt.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.scrollUp.min.js') }}"></script>
        <script src="{{ secure_asset('js/wow.min.js') }}"></script>
        <script src="{{ secure_asset('js/nice-select.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.slicknav.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.magnific-popup.min.js')}}"></script>
        <script src="{{ secure_asset('js/plugins.js') }}"></script>
        <script src="{{ secure_asset('js/gijgo.min.js') }}"></script>
        <!--contact js-->
        <script src="{{ secure_asset('js/contact.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.ajaxchimp.min.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.form.js') }}"></script>
        <script src="{{ secure_asset('js/jquery.validate.min.js') }}"></script>
        <script src="{{ secure_asset('js/mail-script.js') }}"></script>

        <script src="{{ secure_asset('js/main.js') }}"></script>
      




</body>
</html>

resources/views/events/form.blade.php
<div class="form-group">
		        	<label for="title">Title</label>
		        	<input type="text" class="form-control" name="title" id="title">
	        	</div>

	        	<div class="form-group">
	        		<label for="des">Description</label>
	        		<textarea name="description" id="des" cols="20" rows="5" id='des' class="form-control"></textarea>
                </div>
                <div class="form-group">
                  <label>Date range:</label>

                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                      
                        <i class="far fa-calendar-alt"></i>
                      </span>
                    </div>
                    <input type="date" class="form-control float-right" id="date">
                  </div>
                  <!-- /.input group -->
                </div>
                <!-- time Picker -->
                <div class="bootstrap-timepicker">
                  <div class="form-group">
                    <label>Time picker:</label>

                    <div class="input-group date" id="time" data-target-input="nearest">
                      <input type="text" class="form-control datetimepicker-input" data-target="#timepicker"/>
                      <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="far fa-clock"></i></div>
                      </div>
                      </div>
                    <!-- /.input group -->
                  </div>

resources/views/events/index.blade.php
@extends('layouts.master')

@section('content')

<h3>All Events</h3>

<table class="table table-responsive">
<thead>
<tr>
<th>Name</th>
<th>Description</th>
<th>Modify</th>
</tr>
</thead>
<tbody>
<tr>
<td>Name</td>
<td>Description</td>
<td>Modify</td>
</tr>

</tbody>

</table>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Add new
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{ route('events.store') }}" method="post">
      {{csrf_field()}}
      <div class="modal-body">
      @include('events.form')
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
      </form>
    </div>
  </div>
</div>
<!-- EditModal -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Event</h4>
      </div>
      <form action="{{route('events.update','test')}}" method="post">
      		{{method_field('patch')}}
      		{{csrf_field()}}
	      <div class="modal-body">
	      		<input type="hidden" name="events_id" id="cat_id" value="">
				@include('events.form')
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="submit" class="btn btn-primary">Save Changes</button>
	      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal modal-danger fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Delete Confirmation</h4>
      </div>
      <form action="{{route('events.destroy','test')}}" method="post">
      		{{method_field('delete')}}
      		{{csrf_field()}}
	      <div class="modal-body">
				<p class="text-center">
					Are you sure you want to delete this?
				</p>
	      		<input type="hidden" name="events_id" id="cat_id" value="">

	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-success" data-dismiss="modal">No, Cancel</button>
	        <button type="submit" class="btn btn-warning">Yes, Delete</button>
	      </div>
      </form>
    </div>
  </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/head.blade.php
<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>4Hope</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{{ secure_asset('img/favicon.png') }}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{{ secure_asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/themify-icons.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/nice-select.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/flaticon.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/gijgo.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/animate.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/slicknav.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/style.css') }}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <!-- <link rel="stylesheet" href="css/responsive.css"> -->